apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: monitoring
  labels:
    app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
  GRAFANA_ADMIN_PASSWORD: "$(GRAFANA_ADMIN_PASSWORD)"
  SLACK_WEBHOOK_URL: "$(SLACK_WEBHOOK_URL)"
