apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
  labels:
    project: solidarytech
    tier: infra
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: solidarytech
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "65.x"
      helm:
        valueFiles:
          - $values/infra/monitoring/prometheus-values.yaml
    - repoURL: https://github.com/DCLT/1-DCLT-GITOPS-FASE-5
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
