apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  labels:
    project: solidarytech
    tier: infra
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: solidarytech
  sources:
    - repoURL: https://vmware-tanzu.github.io/helm-charts
      chart: velero
      targetRevision: "7.x"
      helm:
        valueFiles:
          - $values/infra/velero/velero-install.yaml
    - repoURL: https://github.com/AXMEDUSA/1-DCLT-GITOPS-FASE-5
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
