# values-datadog.yaml
datadog:
  site: "us5.datadoghq.com"
  credentials:
    apiSecret:
      secretName: "datadog-secret"
      keyName: "api-key"
  clusterName: "aks-solidarytech"
  clusterChecks:
    enabled: true
  orchestratorExplorer:
    enabled: true
  tags:
    - "env:prod"
  apm:
    instrumentation:
      enabled: true
      targets:
        - name: "default-target"
          ddTraceVersions:
            java: "1"
            python: "4"
            js: "5"
            php: "1"
            dotnet: "3"
            ruby: "2"
          ddTraceConfigs:
            - name: "DD_RUM_ENABLED"
              value: "true"
            - name: "DD_RUM_APPLICATION_ID"
              value: "4edf0505-d4a3-42ea-8d79-7ddde1333737"
            - name: "DD_RUM_CLIENT_TOKEN"
              value: "pube3c597c6a75581c1f44ee9089a8b2f45"
            - name: "DD_RUM_REMOTE_CONFIGURATION_ID"
              value: "e654d38f-634d-475f-996a-b0e5f627ed47"
            - name: "DD_RUM_SITE"
              value: "us5.datadoghq.com"
  logs:
    enabled: true
    containerCollectAll: true

providers:
  aks:
    enabled: true

registry: "datadoghq.azurecr.io"