configuration:
  provider: azure
  backupStorageLocation:
    name: default
    provider: azure
    bucket: velero-backups-solidarytech
    config:
      resourceGroup: rg-solidarytech-fase5
      storageAccount: stsolidarytechvelero
      storageAccountKeyEnvVar: AZURE_STORAGE_ACCOUNT_ACCESS_KEY
      subscriptionId: "a30d43ad-b699-44b4-a11f-31636b226495"

  volumeSnapshotLocation:
    name: default
    provider: azure
    config:
      resourceGroup: rg-solidarytech-fase5
      subscriptionId: "a30d43ad-b699-44b4-a11f-31636b226495"

credentials:
  useSecret: true
  existingSecret: velero-credentials

initContainers:
  - name: velero-plugin-for-azure
    image: velero/velero-plugin-for-microsoft-azure:v1.10.0
    volumeMounts:
      - mountPath: /target
        name: plugins

schedules:
  daily-backup-solidarytech:
    schedule: "0 2 * * *"
    template:
      includedNamespaces:
        - solidarytech
      storageLocation: default
      volumeSnapshotLocations:
        - default
      ttl: 720h0m0s
